### PR TITLE
add 'Access-Control-Allow-Origin' = * header

### PR DESCRIPTION
**Pull request by JesseCrocker**
My workflow for developing tile sets involves creating a tileset with some tool(frequently tippecanoe), viewing with mbview for QA, then another QA step where it gets viewed in an existing style. Having mbview send an `Access-Control-Allow-Origin` header eliminates the the need to start another server to serve tiles for that final QA step.

### CODE REVIEW

**Comment by alulsh** [comment]
👋  Hey @JesseCrocker, can you elaborate more on "then another QA step where it gets viewed in an existing style" and "eliminates the the need to start another server to serve tiles for that final QA step." Are these custom servers that you wrote or already existing tools/servers? To confirm - this server is also running locally, right?

**Comment by jingsam** [comment]
@alulsh I don't know how to make #74 merged, can you check that PR, please.

**Comment by JesseCrocker** [comment]
Hi @alulsh, thanks for taking a look at this.

Im using https://github.com/maputnik/editor and sometimes just a local html page running mapbox-gl-js for, either way it needs CORS headers to be able to load the tiles.

And yes, this is all about running on localhost, and fetching tiles from localhost, but CORS headers are still needed because while the host is the same, the port is different.

**Comment by JesseCrocker** [comment]
Closing due to no activity for > 6 months

**Pull request closed without merging**
