### PR TITLE
Load multiple tilesets

### LINKED ISSUE #13: Support multiple sources
An array of MBTiles

### PR DESCRIPTION
**Pull request by rodowi**
Closes #13 

Append as many MBTiles as you need
```bash
✗ node cli.js test/fixtures/sf-01.mbtiles test/fixtures/sf-02.mbtiles
```

Result:

screen shot 2016-05-07 at 11 52 49 pm

### CODE REVIEW

**Comment by rodowi** [comment]
cc: @aaronlidman

**Comment by rodowi** [comment]
- Uses d3-queue to defer the loading of the mb/sqlite interfaces and spin up the server.
- Keeps track of sources in a tilesets hash.
- Template iterates over a sources (tilesets config) hash.

**Comment by aaronlidman** [comment]
This is great! My only suggestion would be to add some logic to ensure that the same random color isn't picked used for different sources.

**Comment by aaronlidman** [comment]
I'm getting this error when using the qa-tiles:
```
TypeError: Cannot read property 'getTile' of undefined
    at /Users/aaron/mbview/mbview.js:78:31
    at Layer.handle [as handle_request] (/Users/aaron/mbview/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/aaron/mbview/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/aaron/mbview/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/aaron/mbview/node_modules/express/lib/router/layer.js:95:5)
    at /Users/aaron/mbview/node_modules/express/lib/router/index.js:277:22
    at param (/Users/aaron/mbview/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/aaron/mbview/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/aaron/mbview/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/aaron/mbview/node_modules/express/lib/router/index.js:365:14)
```

**Comment by aaronlidman** [comment]
I tracked ^ down to how you're using `data.id` here: https://github.com/mapbox/mbview/blob/6b401379c23140ea3db140b5b67c0c5ec982b86c/mbview.js#L36

The id does not relate to the filename, they just happen to be the same with the files you're working with, so I think you want to use `name` instead?

**Comment by rodowi** [comment]
gotcha, cannot getTile of undefined means that tilesets['the_source'] does not exist. Your suggestion is 👌,  Let's keep the `name` var (that is the filename) as the hash key for loading the values corresponding to a source.

**Comment by rodowi** [comment]
@aaronlidman feel free to merge if 7af915b works on your local env

**Comment by aaronlidman** [comment]
screen shot 2016-05-09 at 9 21 50 am

👍

**Comment by rodowi** [comment]
Adding that awesome screenshot to #25

**Pull request merged**
