### PR TITLE
Let tile loading zoom go all the way to the tileset's maxzoom

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by rodowi** [comment]
👍 also adding zoom as cli param [here](https://github.com/mapbox/mbview/blob/6e36ed20675e69fd777be2be79bcb5c425a2b690/cli.js#L29) would be useful.

**Comment by rodowi** [comment]
So, if the Maxzoom is in the tileset metadata as 'maxzoom':

```
*** Metadata found in the MBTiles
{ scheme: 'tms',
  basename: 'tracks.mbtiles',
  id: 'tracks',
  filesize: 282968064,
  name: 'tracks.mbtiles',
  description: 'tracks.mbtiles',
  version: '2',
  minzoom: 10,
  maxzoom: 20,
```

shouldn't we use maxzoom in the map template instead?

**Comment by rodowi** [comment]
Grabbing the maxzoom from the tileset metadata and adding it to the template:

screen shot 2016-05-06 at 5 35 53 pm

**Comment by ericfischer** [comment]
Thanks for catching my mistake @rodowi! Using maxzoom from the metadata seems like the right thing. Tippecanoe always writes the same zoom for the maxzoom and the center, so I hadn't noticed, but for a tileset that comes from Studio Classic, the maxzoom and the center zoom will probably be different.

**Comment by rodowi** [comment]
Awesome @ericfischer, let's merge this!

**Pull request merged**
